#!/bin/bash

case "${BASH_SOURCE[0]}" in
  */*) UNRESOLVED_DIR="${BASH_SOURCE[0]%/*}" ;;
  *) UNRESOLVED_DIR='.' ;;
esac
SCRIPT_DIR="$(cd "${UNRESOLVED_DIR}" &>/dev/null && pwd -P)" || exit "$?"
readonly SCRIPT_DIR

